### ISSUE TITLE
User Profiles Mapping

### ISSUE THREAD

**Issue by AndyBandel** [Yvand/EntraCP#288]
Hi,

we have the effect that an Entra ID user does not use the existing profile.

If we share a site with an Entra ID user and he logs in, a second profile is created, like this example:

![grafik](https://github.com/user-attachments/assets/92f09492-9a06-44d2-a44f-979b61ebabe1)

The first user profile is a synced profile. It comes via Entra ID Domain Service because I haven't found a way to sync the user profiles directly from Entra ID.

Is there a way how we can connect the Entra ID user with his synchronized profile?

**Comment by Srinivasnamala2003** [comment]
Hi Yvand
People picker is not working when take the logs we are seeing below error in the logs please give me the suggestion to resolving the issue
we are configure UPA AZure CCP In Sharepoint Subscription edition version
Error :
[AzureCP] Unexpected error occurred Microsoft.Graph could not query tenant 'EYGS.onmicrosoft.com': System.Net.Http.HttpRequestException: An error occurred while sending the request., Callstack:
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.RedirectHandler.d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.RetryHandler.d__9.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.CompressionHandler.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.AuthenticationHandler.d__16.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.HttpProvider.d__19.MoveNext()

**Comment by Yvand** [comment]
@Srinivasnamala2003 I totally missed your reply on this issue. Given that AzureCP is outdated, I strongly encourage you to [upgrade to EntraCP](https://entracp.yvand.net/overview/introduction/).
