### ISSUE TITLE
People Picker is not working 

### ISSUE THREAD

**Issue by Srinivasnamala2003** [Yvand/EntraCP#299]
Hi Yvand
People picker is not working when take the logs we are seeing below error in the logs please give me the suggestion to resolving the issue
we are configure UPA AZure CCP In Sharepoint Subscription edition version
Error :
[AzureCP] Unexpected error occurred Microsoft.Graph could not query tenant 'EYGS.onmicrosoft.com': System.Net.Http.HttpRequestException: An error occurred while sending the request., Callstack:
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.RedirectHandler.d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.RetryHandler.d__9.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.CompressionHandler.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.AuthenticationHandler.d__16.MoveNext() --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Graph.HttpProvider.d__19.MoveNext()

**Comment by Yvand** [comment]
Hi @Srinivasnamala2003, this error is too generic. Also, AzureCP is outdated and was [replaced by EntraCP](https://entracp.yvand.net/blog/announcing-entracp/), which brings major improvements.
Can you upgrade to EntraCP?

And just 1 remark: It is counter-productive to post your problem on multiple issues, that does not help in any way, and causes multiple people to receive useless notifications

**Comment by Yvand** [comment]
@Srinivasnamala2003 as I mentioned, the error is too generic to determine the cause, but I suggest you test the connectivity to Entra ID using the scripts available on this page: https://entracp.yvand.net/docs-azurecp/help/troubleshooting/

**Comment by Srinivasnamala2003** [comment]
HI Yvand
Where can download the EntraCP package please provide the download the link

**Comment by Yvand** [comment]
@Srinivasnamala2003 you can find the link and the procedure in https://entracp.yvand.net/docs/usage/installation/#download-the-required-assets

**Comment by Srinivasnamala2003** [comment]
HI @Yvand,

After deployed the EntraCP we are not able to see the central admin EntraCP session  option in for add the tenant connection
Could you help us?
![Uploading Screenshot 2024-12-12 013116.jpg…]()

**Comment by Srinivasnamala2003** [comment]
When Run the get-spclaimprovider is not EntraCP after installing the solution

**Comment by Yvand** [comment]
hi @Srinivasnamala2003, you have to follow all the steps in [the documentation](https://entracp.yvand.net/docs/usage/installation/), it requires more steps than a typical wsp file.
In particular, based on your symptoms, I think you merely omitted to activate the features after deploying the solution

**Comment by Srinivasnamala2003** [comment]
Hi Yvaand
below step is failed. connect is failed could you please help us this issue 

Add-Type -AssemblyName "Yvand.EntraCP, Version=1.0.0.0, Culture=neutral, PublicKeyToken=65dc6b5903b51636"
$config = [Yvand.EntraClaimsProvider.EntraCP]::GetConfiguration()
$settings = $config.Settings

# Add a Microsoft Entra ID tenant using a client secret
$tenant = New-Object "Yvand.EntraClaimsProvider.Configuration.EntraIDTenant"
$tenant.Name = "<TENANT>.onmicrosoft.com"
$tenant.ClientId = "<CLIENTID>"
$tenant.ClientSecret = "<CLIENTSECRET>"
$settings.EntraIDTenants.Add($tenant)
$config.ApplySettings($settings, $true)

# Add a Microsoft Entra ID tenant using a client certificate
$tenant = New-Object "Yvand.EntraClaimsProvider.Configuration.EntraIDTenant"
$tenant.Name = "<TENANT>.onmicrosoft.com"
$tenant.ClientId = "<CLIENTID>"
$certPath = "<CERTIFICATE_PFX_FILEPATH>"
$certPassword = ConvertTo-SecureString -String "<CERTIFICATE_PFX_PASSWORD>" -Force -AsPlainText
$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2($certPath, $certPassword, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)
$tenant.ClientCertificateWithPrivateKey = $cert
$settings.EntraIDTenants.Add($tenant)
$config.ApplySettings($settings, $true)

**Comment by Yvand** [comment]
Can you run the script below and return the output:

```powershell
$solution = Get-SPSolution -Identity "EntraCP.wsp"
Get-SPFeature| Where-Object{$_.SolutionId -eq $solution.SolutionId}
```

**Comment by Srinivasnamala2003** [comment]
We are getting below Error when we connect tenant using Client ID and Client Secert 
Error :
Unable to get access token for tenant 'eyuat.onMicrosoft.com': Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
